# fly.toml app configuration file generated for phonebook-backend-misty-night-3623 on 2025-07-25T17:53:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-misty-night-3623'
primary_region = 'mia'

[build]


[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
